# -*- coding: utf-8 -*-

COMBO_ESTADOS = (
    (u'Acre','Acre'),    (u'Alagoas','Alagoas'),    (u'Amapá','Amapá'),    (u'Amazonas','Amazonas'),
    (u'Bahia','Bahia'),    (u'Ceará','Ceará'),    (u'Distrito Federal','Distrito Federal'),
    (u'Espírito Santo','Espírito Santo'),    (u'Goiás','Goiás'),    (u'Maranhão','Maranhão'),
    (u'Mato Grosso','Mato Grosso'),    (u'Mato Grosso do Sul','Mato Grosso do Sul'),
    (u'Minas Gerais','Minas Gerais'),    (u'Pará','Pará'),    (u'Paraíba','Paraíba'),
    (u'Paraná','Paraná'),    (u'Pernambuco','Pernambuco'),    (u'Piauí','Piauí'),
    (u'Rio de Janeiro','Rio de Janeiro'),    (u'Rio Grande do Norte','Rio Grande do Norte'),
    (u'Rio Grande do Sul','Rio Grande do Sul'),    (u'Rondônia','Rondônia'),    (u'Roraima','Roraima'),
    (u'Santa Catarina','Santa Catarina'),    (u'São Paulo','São Paulo'),    (u'Sergipe','Sergipe'),
    (u'Tocantins','Tocantins'),
)

CATEGORIAS_ITENS = (
        (u'Alimentos e bebidas', 'Alimentos e bebidas'),
        (u'Automotivo', 'Automotivo'),
        (u'Automóveis e motocicletas', 'Automóveis e motocicletas'),
        (u'Bebês', 'Bebês'),
        (u'Beleza e saúde', 'Beleza e saúde'),
        (u'Brinquedos', 'Brinquedos'),
        (u'Calçados', 'Calçados'),
        (u'Cama, mesa e banho', 'Cama, mesa e banho'),
        (u'Celulares, smartphones e tablets', 'Celulares, smartphones e tablets'),
        (u'Câmeras e filmadoras', 'Câmeras e filmadoras'),
        (u'Eletrodomésticos', 'Eletrodomésticos'),
        (u'Eletrônicos', 'Eletrônicos'),
        (u'Esporte e lazer', 'Esporte e lazer'),
        (u'Ferramentas', 'Ferramentas'),
        (u'Filmes', 'Filmes'),
        (u'Games', 'Games'),
        (u'Industriais', 'Industriais'),
        (u'Informática', 'Informática'),
        (u'Instrumentos musicais', 'Instrumentos musicais'),
        (u'Jogos', 'Jogos'),
        (u'Livros', 'Livros'),
        (u'Movelaria', 'Movelaria'),
        (u'Papelaria', 'Papelaria'),
        (u'Perfumaria', 'Perfumaria'),
        (u'Produtos de limpeza', 'Produtos de limpeza'),
        (u'Roupas', 'Roupas'),
        (u'Serviços', 'Serviços'),
        (u'Software', 'Software'),
        (u'Viagens', 'Viagens'),
)